rules:
  quoted-strings:
    required: true
    extra-allowed: ["{|}"]
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
